spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: customer-service
              uri: lb://customer-service
              predicates:
                - Path=/api/v1/customer/**

            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/api/v1/product/**,/api/v1/category/**

            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/v1/orders/**

            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/api/v1/payment/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG

server:
  port: 8222
  tomcat:
    accesslog:
      enabled: true
      directory: logs
      prefix: access_log
      suffix: .log
      pattern: '%h %l %u %t "%r" %s %b %D ms'

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    tags:
      application: gateway-service
