spring:
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.value.default.type: paymentConfirmation:org.lefab.payment.kafka.PaymentConfirmation
    consumer:
      group-id: payment-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
          spring.json.value.default.type: org.lefab.payment.dtos.OrderConfirmation
          spring.json.trusted.packages: org.lefab.payment.dtos
          spring.json.use.type.headers: false

  datasource:
    url: jdbc:postgresql://localhost:5433/payment-db
    username: fab
    password: fab
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: true
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1.0.0
    baseline-description: Initial
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:/db/migration
server:
  port: 8093

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    tags:
      application: payment-service