spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/product-db
    username: fab
    password: fab
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: true
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1.0.0
    baseline-description: Initial
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:/db/migration
server:
  port: 8091